const prodacts = [
  {
    id: 1,
    name: "77,99 ₽",
    category: "FruitС картой",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 89,
    rating: 5.1,
    discount: 0,
    image: "../images/index/before-card1.png",
  },
  {
    id: 2,
    name: "44,50 ₽",
    category: "С картой",
    description: "Г/Ц Блинчики с мясом вес, Россия",
    price: "50,50 ₽",
    category2: "Обычная",
    rating: 2,
    discount: 20,
    image: "../images/index/card-fruit1.png",
  },
  {
    id: 3,
    name: "44,50 ₽",
    category: "С картой",
    description: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное",
    price: "50,50 ₽",
    category2: "Обычная",
    rating: 3,
    discount: 20,
    image: "../images/index/card-malako2.png",
  },
  {
    id: 4,
    name: "44,50 ₽",
    category: "С картой",
    description: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное",
    price: "50,50 ₽",
    category2: "Обычная",
    rating: 5,
    discount: 20,
    image: "../images/index/bottle-meat3.png",
  },
  {
    name: "Apple",
    category: "Fruit",
    description: "Red apple beautiful and big ",
    price: 87,
    rating: 5,
    discount: 0,
    image: "https://picsum.photos/200/300/?food12",
  },
  {
    name: "Straberry",
    category: "Fruit",
    description: "The garden strawberry (or simply strawberry",
    price: 87,
    rating: 5,
    discount: 0,
    image: "https://picsum.photos/200/300/?food12",
  },
  {
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    image: "https://picsum.photos/200/300/?food12",
  },
  {
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    image: "https://picsum.photos/200/300/?food12",
  },

  {
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    image: "https://picsum.photos/200/300/?food12",
  },
  {
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    image: "https://picsum.photos/200/300/?food12",
  },
  {
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    image: "https://picsum.photos/200/300/?food12",
  },
  {
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    image: "https://picsum.photos/200/300/?food12",
  },
  {
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    image: "https://picsum.photos/200/300/?food12",
  },
  {
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    image: "https://picsum.photos/200/300/?food12",
  },
  {
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    image: "https://picsum.photos/200/300/?food12",
  },
  {
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    image: "https://picsum.photos/200/300/?food12",
  },
  {
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    image: "https://picsum.photos/200/300/?food12",
  },
  {
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    image: "https://picsum.photos/200/300/?food12",
  },
  {
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    image: "https://picsum.photos/200/300/?food12",
  },
  {
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    image: "https://picsum.photos/200/300/?food12",
  },
  {
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    image: "https://picsum.photos/200/300/?food12",
  },
  {
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    image: "https://picsum.photos/200/300/?food12",
  },
  {
    id: 5,
    name: "44,50 ₽",
    category: "С картой",
    description: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    price: "50,50 ₽",
    category2: "Обычная",
    rating: 4,
    discount: 20,
    image: "../images/index/bottle2.png",
  },
  {
    id: 6,
    name: "159,99 ₽",
    category: "Dairy",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 91,
    rating: 5.2,
    discount: 50,
    image: "../images/index/bottle2.png",
  },
  {
    id: 7,
    name: "599,99 ₽",
    category: "Meat",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 68,
    rating: 5.3,
    discount: 20,
    image: "../images/index/novinka-card1.png",
  },
  {
    id: 8,
    name: "49,39 ₽",
    category: "Dessert",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 61,
    rating: 5.4,
    discount: 20,
    image: "../images/index/card-malako2.png",
  },
  {
    id: 9,
    name: "599,99 ₽",
    category: "Dessert",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 98,
    rating: 2,
    discount: 20,
    image: "../images/index/novinka-card1.png",
  },
  {
    id: 10,
    name: "44,50 ₽",
    category: "Dairy",
    description: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 79,
    rating: 5,
    discount: 0,
    image: "../images/index/bottle-meat3.png",
  },
  {
    id: 11,
    name: "159,99 ₽",
    category: "Meat",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 89,
    rating: 2,
    discount: 50,
    image: "../images/index/bottle2.png",
  },
  {
    id: 12,
    name: "49,39 ₽",
    category: "Fruit",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 61,
    rating: 2,
    discount: 20,
    image: "../images/index/card-malako2.png",
  },
];

let massive_ofisser = [
  {
    id: 1,
    name: "Оформите карту «Северяночка»",
    about: "И получайте бонусы при покупке в магазинах и на сайте",
    img: "../images/index/massive2-img1.png",
  },
  {
    id: 2,
    name: "Покупайте акционные товары",
    about: "И получайте вдвое больше бонусов",
    img: "../images/index/massive2-img2.png",
  },
];

const catalok_Massiv = [
  {
    id: 0,
    img: "../images/catalok/catalok1.png",
    name: "Молоко, сыр, яйцо",
  },
  {
    id: 1,
    img: "../images/catalok/catalok2.png",
    name: "Хлеб",
  },
  {
    id: 2,
    img: "../images/catalok/catalok3.png",
    name: "Фрукты и овощи",
  },
  {
    id: 3,
    img: "../images/catalok/catalok4.png",
    name: "Напитки",
  },
  {
    id: 4,
    img: "../images/catalok/catalok5.png",
    name: "Кондитерские изделия",
  },
  {
    id: 5,
    img: "../images/catalok/catalok6.png",
    name: "Чай, кофе",
  },

  {
    id: 6,
    img: "../images/catalok/catalok7.png",
    name: "Бакалея",
  },
  {
    id: 7,
    img: "../images/catalok/catalok8.png",
    name: "Здоровое питание",
  },
  {
    id: 8,
    img: "../images/catalok/catalok9.png",
    name: "Зоотовары",
  },
  {
    id: 9,
    img: "../images/catalok/catalok10.png",
    name: "Фрукты и овощи",
  },
  {
    id: 10,
    img: "../images/catalok/catalok11.png",
    name: "Напитки",
  },
  {
    id: 11,
    img: "../images/catalok/catalok12.png",
    name: "Кондитерские изделия",
  },
  {
    id: 12,
    img: "../images/catalok/catalok13.png",
    name: "Чай, кофе",
  },
];
